version: '3.8'
services:
  app:
    build: .
    container_name: poke-app
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://pokemon:pokepass@postgres:5432/pokedex
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokepass
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
